### ISSUE TITLE
Esphome new names

### ISSUE THREAD

**Issue by Daafip** [BeardedTinker/SolarWS#3]
Thanks for the project!
couple changes to the naming:
`Bme280` = `bme280_i2c`

and the dallas source has been depreciated: 

```bash
Failed config

dallas: [source weather_station.yaml:90]

  The "dallas" component has been replaced by the "one_wire" component.
  https://esphome.io/components/one_wire.
  - pin: GPIO4
  ```

you should replace the
```yaml
# Detect Dallas sensor address
dallas:
  - pin: GPIO4
 ```

with 

```yaml
one_wire:
  - platform: gpio
    pin: GPIO4
```

Lastly, the pin 33 is reused, in newer version you need

```yaml
# ADC platform helps track status of battery
  - platform: adc
    pin: GPIO33
```

To be 

```yaml
pin:
      number: 33
      allow_other_uses: true
```
